from __future__ import annotations

from gabion.synthesis.emission import render_protocol_stubs


def test_contextvar_emission_single_ambient_value_snapshot() -> None:
    plan = {
        "protocols": [
            {
                "name": "RequestBundle",
                "bundle": ["request_id"],
                "tier": 2,
                "rationale": "Tier-2 bundle",
                "evidence": ["control_context", "decision_surface"],
                "fields": [{"name": "request_id", "type_hint": "str"}],
            }
        ]
    }

    output = render_protocol_stubs(plan, kind="contextvar")

    assert output == (
        "# Auto-generated by gabion dataflow audit.\n"
        "from __future__ import annotations\n"
        "\n"
        "from typing import Any, ContextVar, TypeVar\n"
        "\n"
        "_ContextVarT = TypeVar(\"_ContextVarT\")\n"
        "\n"
        "\n"
        "def _read_contextvar(name: str, carrier: ContextVar[_ContextVarT], default: _ContextVarT) -> _ContextVarT:\n"
        "    \"\"\"Typed helper for reading an ambient context value.\"\"\"\n"
        "    return carrier.get(default)\n"
        "\n"
        "\n"
        "# Suggested ambient bundle: RequestBundle (tier 2)\n"
        "# Bundle fields: request_id\n"
        "# Rationale: Tier-2 bundle\n"
        "# Evidence: control_context, decision_surface\n"
        "_request_id_context: ContextVar[str] = ContextVar(\"request_id\")\n"
        "\n"
        "def get_request_id(default: str) -> str:\n"
        "    \"\"\"Read ambient `request_id` from `_request_id_context`.\"\"\"\n"
        "    return _read_contextvar(\"request_id\", _request_id_context, default)\n"
        "\n"
    )


def test_contextvar_emission_grouped_bundle_snapshot() -> None:
    plan = {
        "protocols": [
            {
                "name": "CtxBundle",
                "bundle": ["tenant", "request_id"],
                "tier": 2,
                "rationale": "Tier-2 bundle",
                "evidence": ["decision_surface", "control_context"],
                "fields": [
                    {"name": "tenant", "type_hint": "str"},
                    {"name": "request_id", "type_hint": "str"},
                ],
            }
        ]
    }

    output = render_protocol_stubs(plan, kind="contextvar")

    assert "# Bundle fields: request_id, tenant" in output
    assert output.index("_request_id_context") < output.index("_tenant_context")
    assert "def get_request_id(default: str) -> str:" in output
    assert "def get_tenant(default: str) -> str:" in output


def test_contextvar_emission_unsupported_case_remains_advisory_snapshot() -> None:
    plan = {
        "protocols": [
            {
                "name": "UnclearBundle",
                "bundle": ["mode"],
                "tier": 3,
                "rationale": "Tier-3 bundle",
                "evidence": ["dataflow"],
                "fields": [{"name": "mode", "type_hint": "str | int"}],
            }
        ]
    }

    output = render_protocol_stubs(plan, kind="contextvar")

    assert "Advisory only: missing control_context evidence" in output
    assert "_mode_context: ContextVar[str | int]" in output
