# gabion:ambiguity_boundary_module
# gabion:grade_boundary kind=semantic_carrier_adapter name=dataflow_indexed_file_scan_alias_adapter_analysis
from __future__ import annotations

"""Analysis-index and post-phase alias groups for the legacy monolith path."""

from gabion.analysis.dataflow.engine.dataflow_indexed_file_scan_alias_contract import (
    AliasGroupSpec,
    alias_group,
    module_alias,
)

ANALYSIS_ALIAS_GROUPS: tuple[AliasGroupSpec, ...] = (
    alias_group(
        'post_phase_analysis',
        'Post Phase Analysis',
        module_alias(
            'gabion.analysis.dataflow.engine.dataflow_post_phase_analyses',
            '_annotation_exception_candidates',
            '_keyword_links_literal',
            '_keyword_string_literal',
            '_refine_exception_name_from_annotations',
            '_build_property_hook_callable_index',
            '_callsite_evidence_for_bundle',
            '_collect_config_bundles',
            '_collect_constant_flow_details',
            '_collect_dataclass_registry',
            '_branch_reachability_under_env',
            '_collect_exception_obligations',
            '_collect_handledness_witnesses',
            '_collect_invariant_propositions',
            '_collect_never_invariants',
            '_combine_type_hints',
            '_eval_bool_expr',
            '_eval_value_expr',
            '_compute_knob_param_names',
            '_format_call_site',
            '_format_type_flow_site',
            '_iter_config_fields',
            '_iter_dataclass_call_bundles',
            '_names_in_expr',
            '_node_in_block',
            '_param_annotations_by_path',
            '_parse_module_source',
            '_split_top_level',
            '_StageCacheSpec',
            '_type_from_const_repr',
            'analyze_decision_surfaces_repo',
            'analyze_constant_flow_repo',
            'analyze_deadness_flow_repo',
            'analyze_unused_arg_flow_repo',
            'analyze_value_encoded_decisions_repo',
            'generate_property_hook_manifest',
        ),
        module_alias(
            'gabion.analysis.dataflow.engine.dataflow_documented_bundles',
            '_iter_documented_bundles',
        ),
        module_alias(
            'gabion.analysis.dataflow.engine.dataflow_ingest_helpers',
            '_collect_functions',
            '_iter_paths',
        ),
        module_alias(
            'gabion.analysis.dataflow.engine.dataflow_ingested_analysis_support',
            '_group_by_signature',
            '_propagate_groups',
            '_union_groups',
            'analyze_ingested_file',
        ),
    ),
    alias_group(
        'analysis_index',
        'Analysis Index',
        module_alias(
            'gabion.analysis.dataflow.engine.dataflow_analysis_index',
            '_FILE_SCAN_PROGRESS_EMIT_INTERVAL',
            '_PROGRESS_EMIT_MIN_INTERVAL_SECONDS',
            '_EMPTY_CACHE_SEMANTIC_CONTEXT',
            '_IndexedPassContext',
            '_IndexedPassSpec',
            '_analysis_index_module_trees',
            '_analysis_index_resolved_call_edges',
            '_analysis_index_resolved_call_edges_by_caller',
            '_analysis_index_stage_cache',
            '_analysis_index_transitive_callers',
            'analyze_file',
            '_analyze_file_internal',
            '_accumulate_function_index_for_tree',
            '_build_analysis_index',
            '_build_function_index',
            '_build_symbol_table',
            '_build_call_graph',
            '_iter_monotonic_paths',
            '_iter_resolved_edge_param_events',
            '_parse_stage_cache_key',
            '_reduce_resolved_call_edges',
            '_run_indexed_pass',
            '_phase_work_progress',
            '_profiling_v1_payload',
            '_sorted_text',
            '_stage_cache_key_aliases',
        ),
    ),
)
