# gabion:boundary_normalization_module
from __future__ import annotations

"""Deadline-runtime compatibility owner during WS-5 migration."""

from gabion.analysis.dataflow.engine.dataflow_deadline_runtime import (
    _CalleeResolutionOutcome,
    _DeadlineArgInfo,
    _DeadlineFunctionCollector,
    _DeadlineFunctionFacts,
    _DeadlineLoopFacts,
    _bind_call_args,
    _build_analysis_index,
    _classify_deadline_expr,
    _collect_call_edges,
    _collect_call_edges_from_forest,
    _collect_call_nodes_by_path,
    _collect_deadline_function_facts,
    _collect_deadline_local_info,
    _collect_recursive_functions,
    _collect_recursive_nodes,
    _deadline_arg_info_map,
    _deadline_loop_forwarded_params,
    _fallback_deadline_arg_info,
    _is_dynamic_dispatch_callee_key,
    _materialize_call_candidates,
    _normalize_snapshot_path,
    _reachable_from_roots,
    _resolve_callee,
    _resolve_callee_outcome,
)

__all__ = [
    "_CalleeResolutionOutcome",
    "_DeadlineArgInfo",
    "_DeadlineFunctionCollector",
    "_DeadlineFunctionFacts",
    "_DeadlineLoopFacts",
    "_bind_call_args",
    "_build_analysis_index",
    "_classify_deadline_expr",
    "_collect_call_edges",
    "_collect_call_edges_from_forest",
    "_collect_call_nodes_by_path",
    "_collect_deadline_function_facts",
    "_collect_deadline_local_info",
    "_collect_recursive_functions",
    "_collect_recursive_nodes",
    "_deadline_arg_info_map",
    "_deadline_loop_forwarded_params",
    "_fallback_deadline_arg_info",
    "_is_dynamic_dispatch_callee_key",
    "_materialize_call_candidates",
    "_normalize_snapshot_path",
    "_reachable_from_roots",
    "_resolve_callee",
    "_resolve_callee_outcome",
]
