"""Static analysis subpackage for Gabion."""

from .dataflow_audit import (
    AnalysisResult,
    AuditConfig,
    analyze_paths,
    apply_baseline,
    build_refactor_plan,
    build_synthesis_plan,
    compute_structure_reuse,
    compute_structure_metrics,
    compute_violations,
    diff_decision_snapshots,
    diff_structure_snapshot_files,
    diff_structure_snapshots,
    load_decision_snapshot,
    load_structure_snapshot,
    load_baseline,
    render_dot,
    render_structure_snapshot,
    render_refactor_plan,
    render_report,
    render_decision_snapshot,
    render_protocol_stubs,
    render_reuse_lemma_stubs,
    render_synthesis_section,
    resolve_baseline_path,
    write_baseline,
)
from .type_fingerprints import (
    PrimeRegistry,
    bundle_fingerprint,
    canonical_type_key,
)

__all__ = [
    "AnalysisResult",
    "AuditConfig",
    "analyze_paths",
    "apply_baseline",
    "build_refactor_plan",
    "build_synthesis_plan",
    "compute_structure_metrics",
    "compute_structure_reuse",
    "compute_violations",
    "diff_decision_snapshots",
    "diff_structure_snapshot_files",
    "diff_structure_snapshots",
    "load_decision_snapshot",
    "load_structure_snapshot",
    "load_baseline",
    "render_dot",
    "render_structure_snapshot",
    "render_refactor_plan",
    "render_report",
    "render_decision_snapshot",
    "render_protocol_stubs",
    "render_reuse_lemma_stubs",
    "render_synthesis_section",
    "resolve_baseline_path",
    "write_baseline",
    "PrimeRegistry",
    "bundle_fingerprint",
    "canonical_type_key",
]
