"""Static analysis subpackage for Gabion."""

from gabion.analysis.core.type_fingerprints import (
    Fingerprint,
    FingerprintDimension,
    PrimeRegistry,
    SynthRegistry,
    TypeConstructorRegistry,
    apply_synth_dimension,
    build_fingerprint_registry,
    build_synth_registry,
    build_synth_registry_from_payload,
    bundle_fingerprint,
    bundle_fingerprint_dimensional,
    bundle_fingerprint_setlike,
    bundle_fingerprint_with_constructors,
    canonical_type_key,
    canonical_type_key_with_constructor,
    fingerprint_bitmask,
    fingerprint_carrier_soundness,
    fingerprint_contains,
    fingerprint_gcd,
    fingerprint_hybrid,
    fingerprint_lcm,
    fingerprint_symmetric_diff,
    fingerprint_to_type_keys,
    fingerprint_to_type_keys_with_remainder,
    format_fingerprint,
    load_synth_registry_payload,
    synth_registry_payload,
)
from gabion.analysis.dataflow.engine.dataflow_contracts import (
    AnalysisResult,
    AuditConfig,
    InvariantProposition,
    ReportCarrier,
)
from gabion.analysis.dataflow.engine.dataflow_ingest_helpers import resolve_analysis_paths
from gabion.analysis.dataflow.engine.dataflow_pipeline import analyze_paths
from gabion.analysis.dataflow.io.dataflow_baseline_gates import (
    apply_baseline,
    load_baseline,
    resolve_baseline_path,
    write_baseline,
)
from gabion.analysis.dataflow.io.dataflow_graph_rendering import render_dot
from gabion.analysis.dataflow.io.dataflow_projection_helpers import (
    report_projection_phase_rank,
    report_projection_spec_rows,
    report_projection_specs,
)
from gabion.analysis.dataflow.io.dataflow_refactor_planning import (
    build_refactor_plan,
    render_refactor_plan,
    render_reuse_lemma_stubs,
)
from gabion.analysis.dataflow.io.dataflow_report_rendering import render_synthesis_section
from gabion.analysis.dataflow.io.dataflow_reporting import compute_violations, render_report
from gabion.analysis.dataflow.io.dataflow_snapshot_contracts import (
    DecisionSnapshotSurfaces,
    StructureSnapshotDiffRequest,
)
from gabion.analysis.dataflow.io.dataflow_snapshot_io import (
    compute_structure_metrics,
    diff_decision_snapshots,
    diff_structure_snapshot_files,
    diff_structure_snapshots,
    extract_report_sections,
    iter_report_sections,
    load_decision_snapshot,
    load_structure_snapshot,
    render_decision_snapshot,
    render_structure_snapshot,
)
from gabion.analysis.dataflow.io.dataflow_structure_reuse import (
    build_analysis_collection_resume_seed,
    compute_structure_reuse,
    project_report_sections,
)
from gabion.analysis.dataflow.io.dataflow_synthesis import (
    build_synthesis_plan,
    render_protocol_stubs,
)

__all__ = [
    "AnalysisResult",
    "AuditConfig",
    "InvariantProposition",
    "ReportCarrier",
    "analyze_paths",
    "apply_baseline",
    "build_refactor_plan",
    "build_analysis_collection_resume_seed",
    "build_synthesis_plan",
    "compute_structure_metrics",
    "compute_structure_reuse",
    "compute_violations",
    "diff_decision_snapshots",
    "diff_structure_snapshot_files",
    "DecisionSnapshotSurfaces",
    "StructureSnapshotDiffRequest",
    "diff_structure_snapshots",
    "extract_report_sections",
    "iter_report_sections",
    "load_decision_snapshot",
    "load_structure_snapshot",
    "load_baseline",
    "project_report_sections",
    "report_projection_phase_rank",
    "report_projection_specs",
    "report_projection_spec_rows",
    "render_dot",
    "render_structure_snapshot",
    "render_refactor_plan",
    "render_report",
    "render_decision_snapshot",
    "render_protocol_stubs",
    "render_reuse_lemma_stubs",
    "render_synthesis_section",
    "resolve_analysis_paths",
    "resolve_baseline_path",
    "write_baseline",
    "PrimeRegistry",
    "Fingerprint",
    "FingerprintDimension",
    "TypeConstructorRegistry",
    "SynthRegistry",
    "apply_synth_dimension",
    "build_fingerprint_registry",
    "build_synth_registry_from_payload",
    "build_synth_registry",
    "bundle_fingerprint_dimensional",
    "bundle_fingerprint",
    "bundle_fingerprint_setlike",
    "bundle_fingerprint_with_constructors",
    "canonical_type_key",
    "canonical_type_key_with_constructor",
    "fingerprint_bitmask",
    "fingerprint_carrier_soundness",
    "fingerprint_contains",
    "fingerprint_gcd",
    "fingerprint_hybrid",
    "fingerprint_lcm",
    "fingerprint_symmetric_diff",
    "fingerprint_to_type_keys_with_remainder",
    "fingerprint_to_type_keys",
    "format_fingerprint",
    "load_synth_registry_payload",
    "synth_registry_payload",
]
